name: Run Immortal UI tests

on:
#  push:
#    branches:
#      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-docker@v1

      # Your Docker commands go here
      - name: Start Testing Services
        run: |
          docker compose-up