name: Run Immortal UI tests Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Docker commands
        run: |
          chmod +x docker-action.sh
          ./docker-action.sh